### ISSUE TITLE
Have releases moved from sourceforge/mirror links to GitHub releases permanently?

### ISSUE THREAD

**Issue by MasterAwesome** [MindTheGapps/13.0.0-arm64#1]
I have a couple of questions

- What is the reasoning behind moving it to Github releases
- Is this a permanent change? and are the other mirrors deprecated/will not be updated?
- How do I track the commit of [MindTheGapps/vendor_gapps](https://gitlab.com/MindTheGapps/vendor_gapps) used to build the release?

**Comment by luk1337** [comment]
Just saying, but we didn't host our builds on SourceForge, we did AFH/codefi.re, both of which were terrible. We aren't going to bother uploading to those anymore, and as for "what commit id", our older releases didn't specify that either, so I can make the new ones do.

**Comment by luk1337** [comment]
>How do I track the commit of [MindTheGapps/vendor_gapps](https://gitlab.com/MindTheGapps/vendor_gapps) used to build the release?

This is now resolved, https://github.com/MindTheGapps/13.0.0-arm64/releases/latest shows commit URL.
