### ISSUE TITLE
MindTheGapps 13.0.0-arm64-20231024_114233 causes LineageOS 20 to fail on Pixel 3 (blueline)

### ISSUE THREAD

**Issue by JonTabor** [MindTheGapps/13.0.0-arm64#3]
I tried using the latest release (MindTheGapps-13.0.0-arm64-20231024_114233.zip) when upgrading my Pixel 3 from LineageOS 19.1 to 20.0, and it would fail upon reboot.  Using one version back of MindTheGapps solved the issue, so something is not right in the latest release (at least on Pixel 3)

**Comment by JonTabor** [comment]
nm, this may have been an issue with my initial download of 20231024_114233

**Comment by luk1337** [comment]
The only difference between them are timestamps inside overlay packages, so this is not correct.
