### ISSUE TITLE
Got Stuck in Verify Account screen

### ISSUE THREAD

**Issue by skvignesh15** [MindTheGapps/13.0.0-arm64#4]
I flashed this zip file along with lineage os 20 on OnePlus 7.

Got this link from official lineage os website.

But in 1st boot I was stuck at Verify existing used password or use Google account to verify..

Then I have to reflash the rom to solve this...

**Comment by javelinanddart** [comment]
This is not an issue with the GApps package. This is an issue you have with FRP. It means you may not have factory resetted the device from the Settings app before installing Lineage.

**Comment by skvignesh15** [comment]
Oh thanks, what should I do next time to avoid this issue?
